
# ===============================
# = DATA SOURCE
# ===============================
spring:
  sql:
    init:
      platform: h2
  datasource:
    url: jdbc:h2:tcp://localhost/./blog
    username: blog
    password: blog1!
    driver-class-name: org.h2.Driver
    dbcp2:
      test-while-idle: true
# ===============================
# = JPA
# ===============================
  jpa:
    open-in-view: false
    database: h2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
