
spring:
  application:
    name: application
# ===============================
# = DATA SOURCE
# ===============================
  sql:
    init:
      platform: h2
  datasource:
    url: jdbc:h2:tcp://localhost/./blog
    username: blog
    password: blog1!
    driver-class-name: org.h2.Driver
    dbcp2:
      test-while-idle: true
# ===============================
# = JPA
# ===============================
  jpa:
    open-in-view: false
    database: h2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
# ===============================
# = CIRCUITBREAKER
# ===============================
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
    instances:
      caller:
        baseConfig: default
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - "*"
  health:
    circuitbreakers:
      enabled: true
# ===============================
# = API_KEY
# ===============================
blog:
  search:
    kakao:
      apiUrl: https://dapi.kakao.com/v2/search/blog
      apiKey: 7b4843241eeb4ede37c0266a61eb65b2

    naver:
      apiUrl: https://openapi.naver.com/v1/search/blog.json
      clientId: xrJxqsiiBIQINqholf6i
      clientSecret: zGx8yPqgPv

logging.level:
  org.hibernate.SQL: debug