
spring:
  application:
    name: application
# ===============================
# = DATA SOURCE
# ===============================
#spring.sql.init.platform=postgresql
#spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/tagroom_app
#spring.datasource.username=tagroomapi
#spring.datasource.password=tagroom1@!Local
#spring.datasource.dbcp2.test-while-idle=true
#spring.datasource.dbcp2.validation-query=SELECT 1
#spring.datasource.driver-class-name=org.postgresql.Driver
# ===============================
# = JPA
# ===============================
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=false
#spring.jpa.properties.hibernate.default_batch_fetch_size=100
blog:
  search:
    kakao:
      apiUrl: https://dapi.kakao.com/v2/search/blog
      apiKey: 7b4843241eeb4ede37c0266a61eb65b2

    naver:
      apiUrl: https://openapi.naver.com/v1/search/blog.json
      clientId: xrJxqsiiBIQINqholf6i
      clientSecret: zGx8yPqgPv