server:
  port: 8080
spring:
  application:
    name: application

blog:
  search:
    kakao:
      apiUrl: https://dapi.kakao.com/v2/search/blog
      apiKey: 7b4843241eeb4ede37c0266a61eb65b2

    naver:
      apiUrl: https://openapi.naver.com/v1/search/blog.json
      clientId: xrJxqsiiBIQINqholf6i
      clientSecret: zGx8yPqgPv