server:
  port: 8080
spring:
  application:
    name: application

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - "*"
  health:
    circuitbreakers:
      enabled: true